spring.application.name=MusicLibrary

# Expose all actuators
management.endpoints.web.exposure.include=*

# Core properties
logging.level.org.springframework=INFO

# Data properties
# Database schema
spring.datasource.url=jdbc:postgresql://localhost:5432/musiclibrary
spring.datasource.username=postgres
spring.datasource.password=postgres
# SQL statement logging
logging.level.org.hibernate.SQL=DEBUG
# SQL values logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Upon startup, tables are dropped then created
spring.jpa.hibernate.ddl-auto=update